server:
  port: 9094

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/notification_websocket?createDatabaseIfNotExist=true
    username: root
    password: Armin#123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
  application:
    name: demo-websocket

logging:
  level:
    com:
      socket: debug

